### PR TITLE
Mustafa

### PR DESCRIPTION
**Pull request by mustafa-tanis21**
Added LoginToTryCloud meth
removed TestBase

### CODE REVIEW

**Review by dianadudic — APPROVED** [review]
DO NOT TOUCH User Stories !!!

**Review by Muhammad-54107 — APPROVED** [review]
Reviewed and Approved

**Review by Muhammad-54107 — APPROVED** [review]
approved

**Review by angelina788 — APPROVED** [review]
Done

**Review by volkan2018 — APPROVED** [review]
approved Mon Feb 1st 2021

**Review by Saltanat2020 — APPROVED** [review]
Approved

**Pull request merged**
