### PR TITLE
Sevara

### PR DESCRIPTION
**Pull request by sevara92**
please review and approve

### CODE REVIEW

**Review by mustafa-tanis21 — APPROVED** [review]
Looks good

**Review by ayah0213 — APPROVED** [review]
good

**Comment by volkan2018** [comment]
reviewed

**Review by volkan2018 — APPROVED** [review]
looks good approved!

**Comment by Muhammad-54107** [comment]
great work ..approved

**Review by Muhammad-54107 — COMMENTED** [review]
approved

**Pull request merged**
