### PR TITLE
Mustafa

### PR DESCRIPTION
**Pull request by mustafa-tanis21**
Organized the packages
Please review and confirm.

### CODE REVIEW

**Comment by angelina788** [comment]
aprooved

**Review by dianadudic — APPROVED** [review]
Great job.

**Review by angelina788 — APPROVED** [review]
update

**Comment by Saltanat2020** [comment]
Updating

**Review by volkan2018 — APPROVED** [review]

**Review by Muhammad-54107 — APPROVED** [review]

**Review by volkan2018 — COMMENTED** [review]
YES!!!

**Pull request merged**
