### PR TITLE
organized the packages (Final packages design)

### PR DESCRIPTION
**Pull request by mustafa-tanis21**
organized the packages (Final packages design)

Please approve

### CODE REVIEW

**Review by angelina788 — APPROVED** [review]
finally

**Review by dianadudic — APPROVED** [review]
Lets finish this

**Comment by Saltanat2020** [comment]
let me try

**Review by Muhammad-54107 — APPROVED** [review]
all done

**Review by Saltanat2020 — APPROVED** [review]
I am still trying

**Pull request merged**
